/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [bbpaddress]
      ,[shares]
      ,[fails]
      ,[height]
      ,[updated]
      ,[Reward]
      ,[Percentage]
      ,[Subsidy]
      ,[SucXMR]
      ,[FailXMR]
      ,[SucXMRC]
      ,[FailXMRC]
      ,[TXID]
      ,[Paid]
      ,[Solved]
      ,[BXMR]
      ,[BXMRC]
  FROM [Saved].[dbo].[Share] order by height desc